### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Ibrram** [Androz2091/discord-player#143]
Hello, I face this error

```javascript
(node:15208) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at new Track (path\to\bot\folder\MBot\node_modules\discord-player\src\Track.js:54:41)
    at Player.play (path\to\bot\folder\MBot\node_modules\discord-player\src\Player.js:340:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promis
e which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_u
nhandled_rejections_mode). (rejection id: 2)
(node:15208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zer
o exit code.
```
I face this error when using the play command following the youtube music link

### dependencies version
DiscordJS: **12.4.1**
DiscordJS Opus: **0.3.3**
Discord Player: **3.0.2**

**Comment by Androz2091** [comment]
Hello, can you show me your code and what you searched? (for example `Despacito`)

**Comment by Ibrram** [comment]
![Code_UfnXowLC8N](https://user-images.githubusercontent.com/29353848/98483035-07c26900-220e-11eb-8bdb-4bc42680b17c.png)

Ex: !play https://youtu.be/I0d8kmZlpmk

**Comment by TasoOneAsia** [comment]
I also am experiencing this issue as well. It *only* seems to appear whenever you send a youtube URL as an argument to the play() method. This issue **does not arise with keywords or any of the other URL options.**

**Investigating further, I narrowed down this specific issue to this section (Line 339):**

<img width="400" alt="Error" src="https://user-images.githubusercontent.com/15652018/98688594-06da2600-2339-11eb-94e8-6c2b12c5be4a.png">

It appears that the Player _probably_ should be referencing the videoDetails subobject returned by `ytdl.getBasicInfo()` rather than the parent object. 

**Here is a print of the videoDetails object:**

<img width="1451" alt="videoDetails Object" src="https://user-images.githubusercontent.com/15652018/98689764-3c334380-233a-11eb-96ee-72d92ee24cd4.png">

**Compare that to the parent object and you can see the issue leading to the undefined errors.**

<img width="1680" alt="Response" src="https://user-images.githubusercontent.com/15652018/98693206-02fcd280-233e-11eb-8d6b-65c17de78410.png">

Feel free to add anything if I missed something large. If I can confirm this is the issue, I'll make a PR when I get a chance.

**Versioning**

- DiscordJS: 12.4.1
- DiscordJS Opus: 0.3.3
- Discord Player: 3.0.2
- Node v.12

**Comment by Androz2091** [comment]
It should be fixed thank you @TasoOneAsia for the informations!
