### ISSUE TITLE
RAM memory overload

### ISSUE THREAD

**Issue by AquamonSE** [Androz2091/discord-player#1486]
Hi! Memory overload is a real issue. The RAM memory keeps stacking after each new track/url loaded into the player. For example after playing two 10-12 hours videos (24/7 lofi playlist) it leaves ram at 2GB. If I then requeue the same track which already should be stored in RAM it adds it another time and this issue keeps growing the RAM to very high numbers. This is only on a single server, I've tried added it on another server and it keeps stacking them.

Does opus not extract only audio or how come one song can be 300-500mb in size?

A fix that flushes the ram of previous song played and/ a fix that lets it use the same url that's already stored in RAM to work on a different server when it plays the same song/url would be appreciated. 👍

 - Node Version: v18.12.1
 - Discord Player Version: latest
 - Discord.js Version: latest
 
 Same issue:
 https://github.com/Androz2091/discord-player/issues/1395

**Comment by skdhg** [comment]
This can be caused by various factors. However, in https://github.com/Androz2091/discord-player/releases/tag/discord-player%406.5.0, I have added `maxSize` and `maxHistorySize` in queue options as a workaround to prevent too many tracks being added to the queue. Since queue is just a list, which is created individually for each guild the bot is in, adding too many tracks can cause a memory leak. Discord Player by default does not set the limit on how many tracks can be queued, so it is upto users to utilize this feature.

```js
await player.play(vc, query, {
    nodeOptions: {
        maxSize: 10000, // allow max 10000 tracks in the queue at a time
        maxHistorySize: 100 // allow max 100 items in queue history (history keeps the record of last played tracks)
    }
});

// alternative
queue.setMaxSize(5000) // allow 5000 max tracks
queue.setMaxHistorySize(50) // only store 50 tracks in the history
```

Keep in mind, it is completely normal for the memory usage to go up if the bot is being used in multiple servers as bot has to independently keep track of the state for each queues.

For those who are basically streaming same track across all servers, there's a better approach to reduce resource usage. You should utilize shared audio player rather than creating individual audio players. A quick example would look something like this:

First of all, create add these two lines.

```js
const { createAudioPlayer } = require('discord-player');
// the above line is equivalent to const { createAudioPlayer } = require('@discordjs/voice');
 
const sharedAudioPlayer = createAudioPlayer();
```

# If you are manually managing the queue
```js
// apply audio player while connecting. If the audio player was already playing, this connection will also start playing the audio in sync
if (!queue.connection) await queue.connect(channel, {
    audioPlayer: sharedAudioPlayer
});
 
// only play if it is the initial play req
// future subscribers will automatically receive audio without having to play a track
if (thisIsInitialPlayRequest()) {
    await queue.node.play(track, { queue: false });
}
```

# If you are using `player.play()`
```js
// with player.play(), this is recommended for initial play only
await player.play(channel, query, {
    connectionOptions: {
        audioPlayer: sharedAudioPlayer
    }
});
```

A shared audio player utilizes significantly lower memory as streaming is done from one single resource (there is only one stream source). This approach is best for radio bots or any other bots who stream same thing across multiple servers.

A disadvantage with this approach is, things like audio filters, volume controls, etc are synced across all servers.

also see https://discord-player.js.org/docs/guides/shared-audio-player for more info.

We will keep optimizing other parts of this lib in the future.
