### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by MrTechnic94** [Androz2091/discord-player#1542]
Hello! How solve this problem (I have this problem only on hosting, on my pc work perfectly):
![obraz](https://user-images.githubusercontent.com/101214823/215330328-7f8e325e-fd87-4e0b-ac42-379d3e883e56.png)
**discord-player**: ``dev``
**discord-player/extractor**: ``4.0.0``

**Comment by skdhg** [comment]
This mostly occurs due to the title you've provided. Titles from youtube dont really work well with this:

Usually youtube title contains `<Music Video Name> | Official Music Video` or something similar, which makes lyrics query fail to return a result. You can try doing manual queries. If things are still not working properly, please report it to https://github.com/zyrouge/node-genius-lyrics
