### ISSUE TITLE
Age restriction

### ISSUE THREAD

**Issue by MrTechnic94** [Androz2091/discord-player#1691]
How can i remove age restriction? Not to display this error `throw new Error("Play request received but track was not provided")`? Ytdl-core and play-dl cookies not working.

**Comment by skdhg** [comment]
playing age restricted video (upon failure) will either throw `status code 410` error (if using ytdl) or will emit `error` event to the queue with the same error object when `skipOnNoStream` is used. `skipOnNoStream` will also skip `Play request received but track was not provided` error.

available since 6.2.0
