### ISSUE TITLE
Destroying queue when using leaveOnEndCooldown even if next song is added

### ISSUE THREAD

**Issue by ixeeek** [Androz2091/discord-player#1728]
**Describe the bug**
When using leaveOnEnd set to true and using some leaveOnEndCooldown e.g. for testing purposes 10 seconds, when bot ends queue, starts counting downwards to leave after specified time, but if next song is added within this time, bot will leave voice channel (when leaveOnEndCooldown reaches 0) even if new song(s) were added to queue.

**To Reproduce**
await client.player.nodes.create(message.guild, {
      metadata: {
        channel: message.channel,
        client: message.guild.members.me,
        requestedBy: message.user
      },
      selfDeaf: true,
      leaveOnEnd: true,
      leaveOnEndCooldown: 10000, <-- set e.g 10 seconds
    });
- Then add song to queue, skip it (or wait until it ends), add new song to queue, within time specified in leaveOnEndCooldown. Bot should leave after new song starts playing. 

**Expected behavior**
When adding new songs to queue, leaveOnEndCooldown function should break.

**Please complete the following information:**
 - Node Version: 18.16.0
 - Discord Player Version: 6.2.0
 - Discord.js Version: 14.9.0

**Comment by skdhg** [comment]
The issue seems to occur if only one track is added within the timeout. Based on the source code, https://github.com/Androz2091/discord-player/blob/a2b32dc40ff06e937dddedc655757daa972fbe58/packages/discord-player/src/Structures/GuildQueue.ts#L751 it cancels the `end` operation if the queue holds at least one track, but in case of a single track (which is being played), it does not live inside the queue so this statement yields `false`. Possible solution for this would be to check if `this.isPlaying()` is yielding `true` instead of checking the number of queued entries.

**Comment by skdhg** [comment]
fixed https://github.com/Androz2091/discord-player/commit/e5339f1a982dae4c3e3a0486137fcb29cb2ffe4b
