### ISSUE TITLE
Deezer Extractor

### ISSUE THREAD

**Issue by 0lom** [Androz2091/discord-player#1852]
i suggest adding a built in Deezer Extractor, because `discord-player-deezer` isn't stable + it will be easier

**Comment by twlite** [comment]
cc @retrouser955

**Comment by retrouser955** [comment]
I disagree with this statement. Discord Player provide an extractor API for the community to add its own extractors. Furthermore, discord-player-deezer is stable. [This issue](https://github.com/retrouser955/discord-player-deezer/issues/4#issue-1960178143) is caused by an interference with discord-player's default attachment extractor. To solve the issue, update discord-player to latest by using `npm install discord-player@latest @discord-player/extractor@latest` or `yarn add discord-player@latest @discord-player/extractor@latest`

**Comment by twlite** [comment]
Instead of introducing yet another extractor in this repository, we have decided to continue developing @retrouser955's deezer extractor in our official [github organization](https://github.com/discord-player/deezer-extractor) of this community. This ensures that deezer extractor **will be stable and up-to-date with discord-player api**.
