### ISSUE TITLE
Spotify thumbnails not working

### ISSUE THREAD

**Issue by louis-dnb** [Androz2091/discord-player#796]
when using a spotify link to play music the thumbnail of the track redirects to a 404 page.

**Comment by DevAndromeda** [comment]
Hello, this could happen any time since we depend upon scrapers rather than official api. We use https://npmjs.com/package/spotify-url-info to parse spotify links. If nothing works properly, you can implement your own spotify **[extractor](https://discord-player.js.org/docs/main/master/extractors/extractor)**
